### ISSUE TITLE
www/mt.html referenced but absent from the repository

### ISSUE THREAD

**Issue by nhradar** [appliedbinf/covid19-event-risk-planner#10]
Yesterday's code update changes ui.R to include www/mt.html, but the file isn't tracked in github.

**Comment by ar0ch** [comment]
That file's specifically not tracked because its for analytics only. I'll add it a stub so that shiny doesn't complain.

**Comment by nhradar** [comment]
Thanks. When _paq (which appears to be provided by mt) isn't available, the map fails to redraw when the  event size changes. I appreciate your work sharing this project with all of us. Thank you.

**Comment by ar0ch** [comment]
Ah,darn. Let me just comments out that include.

**Comment by ar0ch** [comment]
Eh, just added the real Matomo file.  It's not worth the effort to maintain a separate branch for public release
