### ISSUE TITLE
Setup branch protections and PR requirements

### ISSUE THREAD

**Issue by ar0ch** [appliedbinf/covid19-event-risk-planner#15]
- [x] Limit direct push activities to `master`  
- [x] Require changes to master to go through PRs  
- [x] Enforce code review on PRs (allow self reviews)
- [x] Disallow non-linear commits and FF  
- [x] Turn restrictions on for admins too (aka me)

**Comment by ar0ch** [comment]
Now to setup GH Actions to generated the frontend data to help for #14

**Comment by jamesholcomb** [comment]
This would be a welcome addition for my use...storing the generated data in the repo.  Should I hold off developing my own `risk_calc`?  How do you anticipate handling dynamic event sizing?
