### ISSUE TITLE
feature request: display additional data in county estimate tooltip

### ISSUE THREAD

**Issue by jamesholcomb** [appliedbinf/covid19-event-risk-planner#17]
- data_cur date: cases
- data_past date: cases
- population

e.g.

2020-10-28: 250 cases
2020-10-14: 220 cases
population: 8500

Otherwise, it's impossible to infer how risk was calculated.

**Comment by liamwarfield** [comment]
Maybe also add when the data for a county was last updated.

**Comment by ar0ch** [comment]
Site - https://covid19risk.biosci.gatech.edu/usa_risk_counties.csv

Github- https://github.com/appliedbinf/covid19-event-risk-planner/blob/master/usa_risk_counties.csv?raw=true

They'll update automatically twice daily when the site updates

Updated date is also available on the maps now:
![image](https://user-images.githubusercontent.com/6864200/99327940-e70e9a80-282f-11eb-83fa-1dc51a0ea1df.png)
