### ISSUE TITLE
UK data-map matching

### ISSUE THREAD

**Issue by sjbeckett** [appliedbinf/covid19-event-risk-planner#19]
UK is reporting cases in City of London (E09000001) and in Hackney (E09000012) together. Similarly Cornwall (E06000052) and the Isles of Scilly (E06000053) are reported together.
Suggest merging spatial polygons, names (e.g. Hackney and City of London), and population sizes for these areas.

**Comment by ar0ch** [comment]
Merged in dev, will come in with IE/DK maps

**Comment by ar0ch** [comment]
Implemented during the last major update
