### ISSUE TITLE
Odd population data?

### ISSUE THREAD

**Issue by wavemaster447** [appliedbinf/covid19-event-risk-planner#20]
I'm trying to use this model to create a tool for theatres in our county to use to work backwards and determine safe values for reopening (determine target caseload based on permissible risk), but I'm unable to precisely recreate your model.  I'm using the State of PA right now - the data cited lists a population of 12,801,989 and reports current active caseload at 24,574 (from the Real-Time State Level estimate page).  Running the Calc_Risk function on those values for an event of 500, at 1x Ci:
`  p_I <- I / pop`
`  1 - (1 - p_I)**n`
becomes 
`1-(1-(24574/12801989))**500`
or 61%. 

However, the web tool reports 49.6%, which (working backwards) assumes a caseload of 24,574 for a population of 17953987.  
https://i.imgur.com/lOkBeDe.png
So I think the tool is misreporting either active caseload or risk, or using an incorrect population assumption.

If I run the formula again with that incorrect population 17953987 for other scenarios (i.e. event of 50 with at 5x Ci) the results I get match perfectly.  
https://i.imgur.com/2P5yp52.png

Apologies if I'm completely missing something, but I'm just concerned that I can't recreate the results from the tool on my own.  I'm not an R programmer myself, so I may simply be misinterpreting something in your code.

**Comment by ar0ch** [comment]
You're very close, just missing a scaling factor (10/14) we use to convert the last 14 days of cases (the Ci) into a 10day average:

` 1-(1-((24574*10/14)/12801989))**500 = .496 `

**Comment by wavemaster447** [comment]
Gotcha.  So generally speaking, the model is

`p_I <- I*(10/14) / pop`
`1 - (1 - p_I)**n`

where I is the new cases reported in the last 14 days?

**Comment by ar0ch** [comment]
Yep! :)

**Comment by jamesholcomb** [comment]
How is the ascertainment bias applied?

**Comment by ar0ch** [comment]
It's a multiplier on Ci (Ci*asc_bias)
