### ISSUE TITLE
Web Application doesn't load in Firefox on Windows.

### ISSUE THREAD

**Issue by fuzzzerd** [appliedbinf/covid19-event-risk-planner#29]
Tabs load, map does not. Seems to work in Chromium based browsers.

![image](https://user-images.githubusercontent.com/711755/98969176-35403880-24d4-11eb-9bc5-ef1b92feee27.png)

**Comment by ar0ch** [comment]
It loads fine here in Firefox -- bare in mind that depending on the application node you get load balanced to, there might be some slowness in downloading the maps data.  Refreshing usually clears things up
