### ISSUE TITLE
continuous risk rank over time

### ISSUE THREAD

**Issue by Fryguy** [appliedbinf/covid19-event-risk-planner#30]
The continuous risk estimates have a way to sort by rank, and they also have a way to sort by rank on a particular day.  Would it be possible to add a chart showing the rank over time, in order to see the changes in a particular state or all states?  If not rank, then %chance over time, perhaps at a hardcoded or selected event size?

**Comment by ar0ch** [comment]
Figure 3 in our paper does this through August: https://www.nature.com/articles/s41562-020-01000-9 . pdf

We've thought about an update to those plots that show the timeline but haven't had time to really dig into it.
