### ISSUE TITLE
Docker "The application unexpectedly exited."

### ISSUE THREAD

**Issue by bryborge** [appliedbinf/covid19-event-risk-planner#32]
## Brief Overview of Issue

When attempting to run this project in a Docker container and access it (via port forward `3838`), the page is greyed out and the cursor is disabled.  Pulling up the web browser js console, I see the following output:

```
The application unexpectedly exited.

Diagnostic information is private. Please ask your system admin for permission if you need to check the R logs.
[INF]: Connection closed. Info: {"type":"close","code":4503,"reason":"The application unexpectedly exited","wasClean":true}
```

I had to comment out a few lines in the Dockerfile to complete the build and run my container.  The following lines were commented out of the Dockerfile:

```
COPY .rtweet_token.rds /root/.rtweet_token.rds
...
COPY docker_github /root/.ssh/id_rsa
COPY docker_github.pub /root/.ssh/id_rsa.pub
RUN ssh-keyscan -H github.com >> /root/.ssh/known_hosts
...
RUN git clone git@github.com:appliedbinf/covid19-event-risk-planner.git /root/repo
```

## My Question

I saw in [a previous issue](https://github.com/appliedbinf/covid19-event-risk-planner/issues/4) that this application was dockerized for *deployment*.  Are there any plans to make this application run in a docker container for development purposes?

**Comment by ar0ch** [comment]
The application as is should run fine in the docker container. You'll however need to run the update_daily and update_current scripts to get some of the required runtime files. The missing dockerfile artifacts contain authentication tokens, hence aren't checked in. 

Could you run the container interactively with 'bash' as the command. And then run the app with: Rscript -e "shiny::runApp('/srv/shiny-server/', port=3838, host='0.0.0.0')"


I really need to update the documentation but haven't found the time/motivation.

**Comment by bryborge** [comment]
Thank you for the reply!  The application itself appears to be running without the error I described initially after running the `update_daily` and `update_current` scripts inside the container.

```
docker exec -it <container id> bash
$ bash /srv/shiny-server/update_current.sh
$ bash /srv/shiny-server/update_daily.sh
```

I also tried running the container interactively and the command you suggested, and after running the scripts it produced the same result. 👍 

Now the application is navigable.  However, I am getting "Not Found" where the map should have rendered.  Looking at the console, I'm seeing failing GET requests to `http://<server_ip>:3838/5_50.html` (404 Not Found), and `https://matomo.chande.science.matamo.php?...` (502 Bad Gateway).

EDIT:  If I can get this fully running/working locally in a docker container, I would be happy to submit a PR to update the documentation if you'd like.

**Comment by ar0ch** [comment]
I guess I can make this more clear in the docs.  On first run, you need to run almost all the crontab entries


```bash
/srv/shiny-server/makeDailyMaps.sh 0 
/srv/shiny-server/makeDailyPlots.sh
/srv/shiny-server/update_current.sh
/srv/shiny-server/update_daily.sh
```

Just be aware, any of the R scripts that run `get_token()` and `post_tweet()` will be unhappy -- notably the `makeDailyMaps*.R` files.  You can just comment out those to get them to run without error (or just ignore the tweet warnings when they come up)

**Comment by bryborge** [comment]
Wonderful, up and running.  I appreciate the guidance!
