### ISSUE TITLE
Inconsistent Data presented in Real-Time US and State-Level Estimates tab

### ISSUE THREAD

**Issue by OldRFUngineer** [appliedbinf/covid19-event-risk-planner#33]
Lower left corner of page presents data for the 10 day average Ci, while the plot displays data for the 14 day average Ci.
Example: 11/16/20, California, Event size 10,  Ci (88,717)
                                                                             Lower left corner      Plot
Chance someone is COVID19 positive at CI       :  1.6%                          2.22%
Chance someone is COVID19 positive at 5xCI   :   7.7%                         10.68%
Chance someone is COVID19 positive at 10xCI :   14.9%                       20.32%

**Comment by ar0ch** [comment]
I missed these while adding in the averaging -- nice catch!

**Comment by OldRFUngineer** [comment]
The plot data now appears to be correct. However the lower left corner data now reflects the chance someone is COVID19 positive at CI (70,434, presumably the current 10 day average) of 1.3%, 6.2%, and 12% for 1x, 5x, and 10x respectively. The values are still being calculated based on the 10/14 factor applied to the CI of 70,434. Sorry, Engineering habits die hard.

**Comment by ar0ch** [comment]
I see what you mean, this is why "write unit tests" is at the top of my list (yet never seems to get done...)

**Comment by OldRFUngineer** [comment]
From what I see now all is well, Real-Time US and State-Level Estimates data is consistent and presumably within reasonable assumptions. Back in the day, my SW Engineers were forced to write and conduct such tests under Government specification requirements. I had file cabinets worth of these test results. Realizing that this is a project to benefit all people, I feel as if any contribution however small is worthwhile. Keep up the good work. Joe

**Comment by ar0ch** [comment]
Thanks again! 😃
