### ISSUE TITLE
map is down for county/ global risk

### ISSUE THREAD

**Issue by brenly** [appliedbinf/covid19-event-risk-planner#40]
the USA Risk Estimates By County map and the Global Risk Estimates map won't load on the site. not sure if this is a hosting issue. just a quick heads up.the continouous risk estimates and real time estimates is still functional.

**Comment by ar0ch** [comment]
Hey, thanks for the note.  That's really quite strange, taking a look now

**Comment by ar0ch** [comment]
@brenly Are you on a Windows machine and/or using Chrome?

**Comment by brenly** [comment]
yep i was on a windows machine on chrome. it seems to be back up now. might have just been a fluke. closing topic thank you for this amazing tooll!
