### ISSUE TITLE
Ascertainment Bias closer to 3.0

### ISSUE THREAD

**Issue by chonghorizons** [appliedbinf/covid19-event-risk-planner#42]
First, thanks for the code and making this project open. I'm using this for my effort to build a school re-opening calculator. Community prevalence is a key parameter.

With that said, I want to share my investigation into Ascertainment Bias.

Based on the CDC's October Seroprevalence data, I think the Ascertainment Bias for new cases/active cases is closer to 3.0.

I've written this up here:
https://github.com/chonghorizons/covid-estimators/wiki/Ascertainment-Bias

## OPTIONS
0) Do nothing.
1) You might allow people to use 3.0 in the main chart. 
2) You might default to 3.0 or 5.0.
3) (hardest) Pull in the state-by-state ascertainment bias numbers.
  * For NY/NJ data, make adjustments for AscertainmentTotal (Total Infected/Total Tested Positive) and AscertainmentActive (ActiveInfected/ActiveTestedPositive)
  * The seroprevalence data has high uncertainty, so you can't really do a first-differencing of the seroprevalence data waves.
  * You might be willing to use a neighboring-state number. Or try to fill in information for some states using test-positivity as a regressor.

Again, thanks!!!

**Comment by chonghorizons** [comment]
A small aside.

With 16million positive test cases (Dec 14, 2020), an ascertainment bias of 10.0 => 160 million cases. About 50% of the population. I think that's unlikely. We'd be close to herd immunity levels then.

With 16million positive, an ascertainment bias of 5.0 => 80 million cases. About 25% of population. That seems reasonable. Probably on the high range of what I think is real.

16 million positive and ascertainment bias of 1.0 => 5% of US population. I think that is not reasonable. So the importance of ascertainment is still important.

### CDC Seroprevalence in Oct 2020.
Eyeballing the weighted average of the CDC seroprevalence suggests that the mid Oct 2020 seroprevalence (most recent data) was about 8% +/- 3%, suggesting about 26million infected. 
The  US positive test count (via Covid Tracking Project) was about 8 million then.
26/8 = 3.25 +/- 1.25%

**Comment by ar0ch** [comment]
@jsweitz we should probably put this in as a the new default (and take out 10).  I have time this week to do this,

**Comment by ar0ch** [comment]
Deployed today in production
