### ISSUE TITLE
Iowa API issue causing inaccurate risk numbers

### ISSUE THREAD

**Issue by nhradar** [appliedbinf/covid19-event-risk-planner#45]
Iowa's API is causing problems for the NYTimes, so the NYTimes data is not refreshing properly for Iowa county-level data. It looks like the case numbers aren't changing, so the Iowa numbers are artificially low.

It's obvious now that the risk is 0, but was misleading when there was still good 2-week old data left. 

I understand doing something about it opens an entire can of unpleasant worms, alas.

**Comment by ar0ch** [comment]
Yeah, I might go the same route NYT has on their graphics and fully censor the Iowa data. 

I'll note though, it isn't an API issue -- Kim Reynolds in her great wisdom is not releasing Iowa's numbers. :-/

**Comment by nhradar** [comment]
Thanks! I will flog the MPH who imprecisely described the issue to me (though, to be fair, it was probably just assumed that I'd understand the Governor's office was trying to obfuscate data). *sigh*
