### ISSUE TITLE
Czechia data update

### ISSUE THREAD

**Issue by sjbeckett** [appliedbinf/covid19-event-risk-planner#54]
Note that the structure of the data resource for Czechia has changed (I think) this week. The file now includes a new column for id as the first column in the dataset. Could amend:

https://github.com/appliedbinf/covid19-event-risk-planner/blob/b9144962093816bc6e292ed07aefd2f2901999f4/COVID19-Event-Risk-Planner/data_processing/makeDailyMapsEU.R#L346

as 

names(czechData) <- c('id','Date','code','District','Confirmed','Cure','Death')

**Comment by ar0ch** [comment]
Solved in #60 #59
