### ISSUE TITLE
advise website viewers to disable adblockers

### ISSUE THREAD

**Issue by brenly** [appliedbinf/covid19-event-risk-planner#62]
i suggest adding some text prompts advising viewers to disable adblock. the newer features and overlays will prevent the site from working if adblock is turned on in the web browser.

**Comment by freyja-bt** [comment]
Whatever we do, we have to be clear that a) the website doesn't actually have ads and b) what specifically adblock is preventing. Because I don't know a single person who disables adblock when a website asks them to.

**Comment by ar0ch** [comment]
I don't believe there's any  functionality that would be blocked by a typical ad blocker (location auto detection via IP will be blocked but that's not required). 


What's not working when you have ad block enabled? And what ad blocker are you using?

**Comment by brenly** [comment]
`<div id="ss-overlay" class="ss-gray-out" style="display: none;"></div>`

this caused problems previously, causing a massive partial transparent grey overlay that prevented use of the site. deleting that line of text would allow me to use the site. it appears to have been remedied now on the live site, the code still in place but the site usable even with ABP active.
