### ISSUE TITLE
Update the 10:1 ascertainment bias

### ISSUE THREAD

**Issue by LucyMcGowan** [appliedbinf/covid19-event-risk-planner#7]
The ascertainment bias is a bit outdated for most places - it would be fabulous to have a slider with a few options 
https://github.com/appliedbinf/covid19-event-risk-planner/blob/078498611b4ca2c5ae8842e5bbc9780508e717b3/COVID19-Event-Risk-Planner/makeDailyMaps.R#L45

My understanding from looking at #6 is that you are pre-rendering the maps, so this could substantially add to that, but perhaps just allowing for 3 options (1:10, 1:5, 1:2) would suffice?

**Comment by ar0ch** [comment]
Hi Lucy,

Thanks for the suggestion!  🙂 

We had a team meeting yesterday and are likely going to add in additional bias options. We're however still working on the messaging -- we don't want to give people too many choices, choices they don't understand or minimize the potential risk. The modeling folks will decide the final options, but I'm guessing we'll add a 2 (or 3), 5 and 10x option.  I'll update this issue to track progress

**Comment by LucyMcGowan** [comment]
Awesome. I agree it's challenging to decide what to do. Another option would be to use something like death data and IFR, so that it could be location specific. This obviously also has challenges with lags, etc.

**Comment by ar0ch** [comment]
Today, CDC released new serology reports: https://www.cdc.gov/coronavirus/2019-ncov/cases-updates/commercial-labs-interactive-serology-dashboard.html

Dr. Weitz summarized it this thread: https://twitter.com/joshuasweitz/status/1285657293040881664 

```

Median from the @CDCgov new sero reports: 9x-10x 
```
_____
```

Here's what the @CDCgov's recent serological survey data found:

UT: >2x
MN: >3x
CT: >4x
Philadelphia: >4x
SF: >9x
West Washington: >9x
South Florida: >10x
NYC: >10x
MO: >13x
LA: >16x
```


We'll be adding in toggles for 2x, 5x, and 10x.


- [x] Documentation for tutorial page  
- [x] Tooltip / short desc. for maps   
- [x] Add in toggles

**Comment by ar0ch** [comment]
@seolhalee has prepared the UI/rendering changes needed https://github.com/seolhalee/edit-covid19-risk-planner-map

**Comment by ar0ch** [comment]
Mallory send over the documentation bits last night.  Now it just needs to be put together.


- [x] Test on dev  
- [x] Deploy to prod machines {01..04}

**Comment by ar0ch** [comment]
@LucyMcGowan We now make maps available at 5x and 10x bias levels.  We decided against 2x, since it appears that UT is an outlier here and we don't want to give a false sense of safety.

![image](https://user-images.githubusercontent.com/6864200/88676122-b4426a00-d0b9-11ea-88b7-bbd09c6c287b.png)

**Comment by LucyMcGowan** [comment]
Fabulous, thank you so much 🙏
