### ISSUE TITLE
Issue with methodology

### ISSUE THREAD

**Issue by bpben** [appliedbinf/covid19-event-risk-planner#8]
Hi,
  Not sure if this is the right place to raise this, but my understanding of the method being applied here is to assess risk as a function of state/county-level cases / state/count-level population.  Is there any adjustment being done for the fact that events are somewhat unlikely to just draw people from the same state and very unlikely to just draw people from the same county? Looking at the map for 1k-person events, I see urban areas with vastly different risk estimates even though an event with 1k people is very likely to draw participants from the surrounding area.

  Maybe I'm missing it in the code.  It seems like there should be a spatial/density component here.

**Comment by ar0ch** [comment]
Hi Ben,

You're right that we're not taking into account people coming from different states/counties.  We've intentionally kept the model very simple and made the fewest assumptions possible.  However, bear in mind an 'event' in the context of our model can be going out to eat at a restaurant or going to a crowed beach -- it isn't limited to concerts, etc.  Mid-sized restaurants can easily accommodate >50 people, and we've all seen images of packed bars and beaches with no social distancing or mask usage.

**Comment by bpben** [comment]
Appreciate the reply.  But isn't there a concern that any of these events
incorporate people from surrounding areas, the larger ones being more
likely to draw people, especially if the population density of the area is
high? Looking at my own area, it's 22% risk for a 1k event in Cambridge,
MA, and 53% in Boston, MA.  It seems like there's a real danger of
under-estimating risk in areas that have a lot of out-of-county visitors
(e.g. beaches).

**Comment by ar0ch** [comment]
Yes, there is that concern and in those cases we could be both under and over estimating risk, again depending on the area.  Unfortunately, without a significantly more complicated model it's hard to quantify that for each locality.

**Comment by bpben** [comment]
I understand there's limited bandwidth, but it does seem like providing
risk estimates at the county level is misleading.  A simple modification
could just be averaging the adjacent counties or building in some kind of
spatial decay.  If it's helpful, I can investigate what's available.

I do think it's worth adding this caveat somewhere in the documentation, I
can imagine the results on the display page (
https://covid19risk.biosci.gatech.edu/) giving people the wrong idea about
their relative safety.

**Comment by ar0ch** [comment]
Unfortunately this is out of scope for this particular application.  Our GIS expert is interested in this sort of work, and has the data to potentially do it.  There is however limited bandwidth.
